TEST: Fail pipeline for liniting

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,3 +12,12 @@ jobs:
 
       - name: Terraform Lint
         uses: actionshub/terraform-lint@1.0.0
+
+      - name: Check Terraform Linting Result
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "Terraform linting passed."
+          else
+            echo "Terraform linting failed."
+            exit 1
+          fi
